### ISSUE TITLE
[1.10.2] Error loading EnderCore (1.10.2-0.4.1.47)

### ISSUE THREAD

**Issue by Messorix** [SleepyTrousers/EnderCore#59]
For my own mod, I want to test if an item is capable of using rf.
To do so I thought I'd use EnderIO (and therefore EnderCore) to charge it.
Sadly I get this error:

`java.lang.NoSuchMethodError: net.minecraft.util.text.translation.I18n.func_74837_a(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String`

Full crash-report:
[crash-2016-08-11_15.16.58-client.txt](https://github.com/SleepyTrousers/EnderCore/files/413333/crash-2016-08-11_15.16.58-client.txt)

I'm unsure if this is a known error, since I couldn't find it here.

**Comment by HenryLoenwind** [comment]
are you in a dev env with endercore in the run/mods folder? If so, remove that "-DFORGE_FORCE_FRAME_RECALC=true" parameter Forge adds.

**Comment by Messorix** [comment]
I have a dev env in which I have put the EC jar-file in the regular mod folder (not sure if that was what you meant)
If so, I don't really know where that parameter is added...

**Comment by tterrag1098** [comment]
Unless forge did something really stupid, that method still exists and is not even client-only. I have no idea how this crash is possible, but I would start by testing with ONLY EC.

**Comment by Messorix** [comment]
Even with only EC in it (same version) I get the same error.
[crash-2016-08-12_12.04.16-client.txt](https://github.com/SleepyTrousers/EnderCore/files/415062/crash-2016-08-12_12.04.16-client.txt)

**Comment by HenryLoenwind** [comment]
That's the command line parameter Forge adds. No mod I tried has ever worked in 1.8.9+ with that parameter present.

How do you start your client? If it's with Eclipse's launch profile, you can edit it from the fold-down menu of the launch button.

**Comment by Messorix** [comment]
I used bedrockminer's tutorial to set my dev env up.
[http://bedrockminer.jimdo.com/modding-tutorials/set-up-minecraft-forge/set-up-advanced-setup/](url)

**Comment by HenryLoenwind** [comment]
I've had a look at that tutorial. I posted some comment there, let me repeat it here:

Um, this is kinda wrong and will lead to all kinds of problems. The "Create the Forge root directory" step is ok, but then:

* Start Eclipse
* Select "File"->"Import..."
* Select "General", "Existing Projects into Workspace"
* Press "Next >"
* For "root directory" select the directory you installed Forge to (the one with the gradlew.bat)
* Check that a project is listed in the "Projects" list
* Do NOT check "Copy projects into workspace"!
* Press Finish

Eclipse will now open the eclipse project that was created by the "gradlew eclipse" step. This project already contains suitable launch profiles for client and server.

For your launch configuration:

![image](https://cloud.githubusercontent.com/assets/1485873/17624697/07693408-60a6-11e6-9f17-5776cd82dfe8.png)

**Comment by Messorix** [comment]
Thank you so much for fixing my dev env. I'm still messing about with getting my project back to work, but after that I'll tell you if EC still crashes or if this fixed it all.

**Comment by Messorix** [comment]
New post so it is very clear: this did NOT fix the error

**Comment by HenryLoenwind** [comment]
Try this: http://loenwind.info/EnderCore-1.10.2-0.4.1.test1-beta.jar

**Comment by Messorix** [comment]
Sooooo... the EC works, but the EnderIO doesn't recognise it as a newer version, so that still doesn't work :P

**Comment by HenryLoenwind** [comment]
ok, then I know what's causing this.
